/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.uniska.pbo2.p03;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

public class FormTiketTravel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTiketTravel.class.getName());

    /**
     * Creates new form FormTiketTravel
     */
    public FormTiketTravel() {
        initComponents();
        
            namaPemesanField.putClientProperty(
            "JTextField.placeholderText",
            "Nama sesuai KTP"
        );

        nomorHpField.putClientProperty(
            "JTextField.placeholderText",
            "08xxxxxxxxxx"
        );

        getRootPane().setDefaultButton(pesanButton);

        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kelasGroup = new javax.swing.ButtonGroup();
        namaPemesanLabel = new javax.swing.JLabel();
        namaPemesanField = new javax.swing.JTextField();
        nomorHpLabel = new javax.swing.JLabel();
        nomorHpField = new javax.swing.JTextField();
        kotaTujuanLabel = new javax.swing.JLabel();
        kotaTujuanCombo = new javax.swing.JComboBox<>();
        kelasLabel = new javax.swing.JLabel();
        ekonomiRadio = new javax.swing.JRadioButton();
        bisnisRadio = new javax.swing.JRadioButton();
        eksekutifRadio = new javax.swing.JRadioButton();
        fasilitasLabel = new javax.swing.JLabel();
        bagasiCheck = new javax.swing.JCheckBox();
        makanCheck = new javax.swing.JCheckBox();
        asuransiCheck = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        catatanArea = new javax.swing.JTextArea();
        catatanLabel = new javax.swing.JLabel();
        pesanButton = new javax.swing.JButton();
        temaToggle = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pemesanan Tiket Travel");

        namaPemesanLabel.setText("Nama Pemesan");

        namaPemesanField.addActionListener(this::namaPemesanFieldActionPerformed);

        nomorHpLabel.setText("Nomor HP");

        kotaTujuanLabel.setText("Kota Tujuan");

        kotaTujuanCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BANJARBARU", "MARTAPURA", "PALANGKARAYA", "SAMARINDA", "BALIKPAPAN" }));

        kelasLabel.setText("Kelas");

        kelasGroup.add(ekonomiRadio);
        ekonomiRadio.setSelected(true);
        ekonomiRadio.setText("Ekonomi");
        ekonomiRadio.addActionListener(this::ekonomiRadioActionPerformed);

        kelasGroup.add(bisnisRadio);
        bisnisRadio.setText("Bisnis");
        bisnisRadio.addActionListener(this::bisnisRadioActionPerformed);

        kelasGroup.add(eksekutifRadio);
        eksekutifRadio.setText("Eksekutif");
        eksekutifRadio.addActionListener(this::eksekutifRadioActionPerformed);

        fasilitasLabel.setText("Fasilitas");

        bagasiCheck.setText("Bagasi");

        makanCheck.setText("Makan");

        asuransiCheck.setText("Asuransi");

        catatanArea.setColumns(20);
        catatanArea.setRows(3);
        jScrollPane1.setViewportView(catatanArea);

        catatanLabel.setText("Catatan :");

        pesanButton.setText("Pesan");
        pesanButton.addActionListener(this::pesanButtonActionPerformed);

        temaToggle.setText("Mode Gelap");
        temaToggle.addActionListener(this::temaToggleActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(namaPemesanLabel)
                        .addGap(18, 18, 18)
                        .addComponent(namaPemesanField, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomorHpLabel)
                            .addComponent(kotaTujuanLabel)
                            .addComponent(kelasLabel)
                            .addComponent(fasilitasLabel)
                            .addComponent(catatanLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bagasiCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(makanCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(asuransiCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ekonomiRadio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bisnisRadio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(eksekutifRadio)))
                                .addContainerGap(155, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(temaToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(pesanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(kotaTujuanCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomorHpField, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaPemesanLabel)
                    .addComponent(namaPemesanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomorHpLabel)
                    .addComponent(nomorHpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kotaTujuanLabel)
                    .addComponent(kotaTujuanCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kelasLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ekonomiRadio)
                        .addComponent(bisnisRadio)
                        .addComponent(eksekutifRadio)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fasilitasLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bagasiCheck)
                        .addComponent(makanCheck)
                        .addComponent(asuransiCheck)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(catatanLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(temaToggle)
                    .addComponent(pesanButton))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ekonomiRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekonomiRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ekonomiRadioActionPerformed

    private void bisnisRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bisnisRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bisnisRadioActionPerformed

    private void eksekutifRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eksekutifRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eksekutifRadioActionPerformed

    private void pesanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanButtonActionPerformed
    tampilkanRingkasan();        // TODO add your handling code here:
    }//GEN-LAST:event_pesanButtonActionPerformed

    private void temaToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temaToggleActionPerformed
    gantiTema(temaToggle.isSelected());        // TODO add your handling code here:
    }//GEN-LAST:event_temaToggleActionPerformed

    private void namaPemesanFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPemesanFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPemesanFieldActionPerformed
   
    private void gantiTema(boolean gelap) {

        if (gelap) {
            FlatDarkLaf.setup();
        } else {
            FlatLightLaf.setup();
        }

        FlatLaf.updateUI();

        temaToggle.setText(
            gelap ? "Mode Terang" : "Mode Gelap"
        );
    }
    private void tampilkanRingkasan() {

        String kelas;

        if (ekonomiRadio.isSelected()) {
            kelas = "Ekonomi";
        } else if (bisnisRadio.isSelected()) {
            kelas = "Bisnis";
        } else {
            kelas = "Eksekutif";
        }

        List<String> fasilitas = new ArrayList<>();

        for (JCheckBox cb : List.of(
                bagasiCheck,
                makanCheck,
                asuransiCheck)) {

            if (cb.isSelected()) {
                fasilitas.add(cb.getText());
            }
        }

        String pesan =
                "Nama Pemesan: " + namaPemesanField.getText()
                + "\nNomor HP: " + nomorHpField.getText()
                + "\nKota Tujuan: " + kotaTujuanCombo.getSelectedItem()
                + "\nKelas: " + kelas
                + "\nFasilitas: "
                + (fasilitas.isEmpty()
                    ? "-"
                    : String.join(", ", fasilitas))
                + "\nCatatan: " + catatanArea.getText();

        JOptionPane.showMessageDialog(
                this,
                pesan,
                "Ringkasan Pemesanan",
                JOptionPane.INFORMATION_MESSAGE
        );
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();

        java.awt.EventQueue.invokeLater(
            () -> new FormTiketTravel().setVisible(true)
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox asuransiCheck;
    private javax.swing.JCheckBox bagasiCheck;
    private javax.swing.JRadioButton bisnisRadio;
    private javax.swing.JTextArea catatanArea;
    private javax.swing.JLabel catatanLabel;
    private javax.swing.JRadioButton ekonomiRadio;
    private javax.swing.JRadioButton eksekutifRadio;
    private javax.swing.JLabel fasilitasLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup kelasGroup;
    private javax.swing.JLabel kelasLabel;
    private javax.swing.JComboBox<String> kotaTujuanCombo;
    private javax.swing.JLabel kotaTujuanLabel;
    private javax.swing.JCheckBox makanCheck;
    private javax.swing.JTextField namaPemesanField;
    private javax.swing.JLabel namaPemesanLabel;
    private javax.swing.JTextField nomorHpField;
    private javax.swing.JLabel nomorHpLabel;
    private javax.swing.JButton pesanButton;
    private javax.swing.JToggleButton temaToggle;
    // End of variables declaration//GEN-END:variables
}
